### ISSUE TITLE
got error when run cloud function 'feed'

### ISSUE THREAD

**Issue by zx9597446** [GetStream/Stream-Example-Parse#2]
E2015-02-27T08:10:26.094Z]v652 Ran cloud function feed with:
  Input: {"feed":"user:IXb7HGtnc2","id_lte":0,"limit":3}
  Result: ReferenceError: setTimeout is not defined
    at nextTick (getstream.js:17488:9)
    at onwrite (getstream.js:18970:7)
    at WritableState.onwrite (getstream.js:18804:5)
    at afterTransform (getstream.js:18585:5)
    at TransformState.afterTransform (getstream.js:18560:12)
    at Hash._transform (getstream.js:10676:3)
    at Hash.Transform._read (getstream.js:18665:10)
    at Hash.Transform._write (getstream.js:18653:12)
    at doWrite (getstream.js:18931:10)
    at writeOrBuffer (getstream.js:18921:5)

clound function 'feed':
/*
- View to retrieve the feed, expects feed in the format user:1
- Accepts params
  *
- feed: the feed id in the format user:1
- limit: how many activities to get
- id_lte: filter by activity id less than or equal to (for pagination)
  *
  */
  Parse.Cloud.define("feed", function(request, response) {
  var feedIdentifier = request.params.feed;
  var feedParts = feedIdentifier.split(':');
  var feedSlug = feedParts[0];
  var userId = feedParts[1];
  var id_lte = request.params.id_lte || undefined;
  var limit = request.params.limit || 100;
  var params = {
      limit : limit
  };
  if (id_lte) {
      params.id_lte = limit;
  }
  // initialize the feed class
  var feed = client.feed(feedSlug, userId);
  feed.get(params, function(httpResponse) {
      var activities = httpResponse.data;
      // enrich the response with the database values where needed
      var promise = utils.enrich(activities.results);
      promise.then(function(activities) {
          response.success({
              activities : activities,
              feed : feedIdentifier,
              token : feed.token
          });
      });
  }, utils.createHandler(response));
  });

please help me find out what's wrong.

**Comment by tschellenbach** [comment]
We've so far traced this down to the js crypto library which no longer works with parse cloud code.

**Comment by tschellenbach** [comment]
this has been fixed, it's an ugly hack, but it works for now
