### ISSUE TITLE
failed to query the data needed for enrichment

### ISSUE THREAD

**Issue by jgiovanni** [GetStream/Stream-Example-Parse#3]
I run the code: 

``` javascript
Parse.Cloud.run("feed", {feed: "user:dcyRc65vUR:",limit:3 })
```

I have not altered the cloud "feed" function. This is the full error message from the Parse Logs
E2015-11-06T17:23:41.402Z]v10 Ran cloud function feed for user dcyRc65vUR with:
  Input: {"feed":"user:dcyRc65vUR:","limit":3}
  Result: success/error was not called
I2015-11-06T17:23:41.757Z]failed to query the data needed for enrichment

I've tried to troubleshoot, but no luck. Some help would be awesome!

**Comment by tbarbugli** [comment]
perhaps you deleted something from Parse but not from the feed? I suggest
you to have a look and compare the content of the user feed (using the
databrowser) and see if there are any missing references. reach us at
support if you need more help with this.
